const fs=require('fs'),path=require('path');
const {ROOT,QAOUT,data,serve,state,frameClock,launch}=require('./browser_common.cjs');
async function steps(page,n=25){await page.evaluate(n=>{for(let i=0;i<n;i++)window.__captureClock.step(50);},n);}
async function overlays(page){return page.evaluate(()=>Array.from(document.querySelectorAll('#error,#loading,#status,#toast')).map(e=>({id:e.id,text:e.textContent.trim(),visible:!!(e.getBoundingClientRect().width&&e.getBoundingClientRect().height)&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden'&&!e.hidden,opacity:getComputedStyle(e).opacity})));}
(async()=>{const {server,url}=await serve(),browser=await launch(),results=[];
try{for(const s of data){const prefix=String(s.order).padStart(2,'0'),r={order:s.order,errors:[],messages:[]};const context=await browser.newContext({viewport:{width:1280,height:720},deviceScaleFactor:1,reducedMotion:'no-preference'});await context.addInitScript(frameClock);const page=await context.newPage();page.on('pageerror',e=>r.errors.push(String(e)));page.on('console',e=>{if(/context/i.test(e.text()))r.messages.push(e.text());});await page.goto(url+'/scenes/'+prefix+'.html',{waitUntil:'load'});await steps(page,40);await page.waitForTimeout(800);r.before=await state(page);
 r.extensionAvailable=await page.evaluate(()=>{const c=document.querySelector('canvas'),gl=c.getContext('webgl2')||c.getContext('webgl');const ext=gl.getExtension('WEBGL_lose_context');window.__lossProbe={gl,ext,events:[]};for(const type of ['webglcontextlost','webglcontextrestored'])c.addEventListener(type,e=>window.__lossProbe.events.push({type,bubbles:e.bubbles,defaultPrevented:e.defaultPrevented}));if(ext)ext.loseContext();return!!ext;});
 await page.waitForTimeout(600);await steps(page);r.lost=await state(page);r.lostOverlays=await overlays(page);await page.evaluate(()=>window.__lossProbe.ext?.restoreContext());await page.waitForTimeout(1300);await steps(page,30);r.restored=await state(page);r.restoredOverlays=await overlays(page);r.events=await page.evaluate(()=>window.__lossProbe.events);await page.screenshot({path:path.join(QAOUT,'evidence',prefix+'-context-restored.png')});results.push(r);fs.writeFileSync(path.join(QAOUT,'context-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({order:r.order,events:r.events,lostDistance:r.lost.distance,restoredDistance:r.restored.distance,overlays:r.restoredOverlays,errors:r.errors}));await context.close();}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
